[package]
name = "input"
version = "0.1.0"
authors = ["cunitac <cunitac@gmail.com>"]
edition = "2018"
license = "MIT"

[features]
default = []
interactive = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
