[package]
name = "capture-fn"
version = "0.1.0"
authors = ["cunitac <cunitac@gmail.com>"]
edition = "2018"
license = "MIT"
lib = "capture_fn"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
