[package]
name = "disjoint_set"
version = "0.1.0"
edition = "2018"
author = ["cunitac <cunitac@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
